// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://obvidsdcfugvrajsmubu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9idmlkc2RjZnVndnJhanNtdWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjMwMTksImV4cCI6MjA3Mzc5OTAxOX0.qYxrKbP4IeNZnoWksbfpyx22aGQR4zv9i3CUXsQG3cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);